{ ... }:

{
  xdg.configFile."nvim/init.lua".text = ''
-- =============================================================================
-- Neovim IDE Configuration
-- Generated by NixOS Home Manager
-- =============================================================================

require 'core.options'
require 'core.keymaps'

-- Set up Lazy plugin manager
local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
  local out = vim.fn.system { 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath }
  if vim.v.shell_error ~= 0 then
    error('Error cloning lazy.nvim:\n' .. out)
  end
end
vim.opt.rtp:prepend(lazypath)

-- Load plugins
require('lazy').setup({
  -- Theme
  {
    'navarasu/onedark.nvim',
    lazy = false,
    priority = 1000,
    opts = {
      style = 'dark',
      transparent = true,
      term_colors = true,
      code_style = {
        comments = 'italic',
        keywords = 'none',
        functions = 'none',
        strings = 'none',
        variables = 'none',
      },
      diagnostics = {
        darker = true,
        undercurl = true,
        background = true,
      },
    },
    config = function(_, opts)
      require('onedark').setup(opts)
      require('onedark').load()
    end,
  },

  -- Core utilities
  { 'nvim-lua/plenary.nvim' },

  -- UI
  require 'plugins.lualine',
  require 'plugins.which-key',
  require 'plugins.dressing',
  require 'plugins.notify',

  -- File explorer
  require 'plugins.neotree',

  -- Git
  require 'plugins.gitsigns',

  -- LSP
  require 'plugins.lsp',
  require 'plugins.cmp',

  -- Treesitter
  require 'plugins.treesitter',

  -- Fuzzy finding
  require 'plugins.telescope',

  -- Motion
  require 'plugins.hop',

  -- Utilities
  require 'plugins.autopairs',
  require 'plugins.todo-comments',

  -- LaTeX
  require 'plugins.vimtex',
})
'';
}
